insert into possivel_escolha(id, restaurante_lado_esquerdo , restaurante_lado_direito)  values (1, 'BurgerKing', 'McDonalds')
insert into possivel_escolha (id, restaurante_lado_esquerdo , restaurante_lado_direito) values (2, 'KFC', 'McDonalds')
insert into possivel_escolha (id, restaurante_lado_esquerdo , restaurante_lado_direito) values (3, 'Outback', 'McDonalds')
insert into possivel_escolha (id, restaurante_lado_esquerdo , restaurante_lado_direito) values (4, 'Subway', 'McDonalds')
insert into possivel_escolha (id, restaurante_lado_esquerdo , restaurante_lado_direito) values (5, 'KFC', 'BurgerKing')
insert into possivel_escolha (id, restaurante_lado_esquerdo , restaurante_lado_direito) values (6, 'Outback', 'BurgerKing')
insert into possivel_escolha (id, restaurante_lado_esquerdo , restaurante_lado_direito) values (7, 'Subway', 'BurgerKing')
insert into possivel_escolha (id, restaurante_lado_esquerdo , restaurante_lado_direito) values (8, 'Outback', 'KFC')
insert into possivel_escolha (id, restaurante_lado_esquerdo , restaurante_lado_direito) values (9, 'Subway', 'KFC')
insert into possivel_escolha (id, restaurante_lado_esquerdo , restaurante_lado_direito) values (10,'Subway', 'Outback')

