insert into restaurante(id,nome) values(1, 'McDonalds')
insert into restaurante(id,nome) values(2, 'BurgerKing')
insert into restaurante(id,nome) values(3, 'KFC')
insert into restaurante(id,nome) values(4, 'Outback')
insert into restaurante(id,nome) values(5, 'Subway')

insert into possivel_escolha (id, restauranteLadoEsquerdo_id , restauranteLadoDireito_id)  values (1,2, 1)
insert into possivel_escolha (id, restauranteLadoEsquerdo_id , restauranteLadoDireito_id) values (2, 3, 1)
insert into possivel_escolha (id, restauranteLadoEsquerdo_id , restauranteLadoDireito_id) values (3, 4, 1)
insert into possivel_escolha (id, restauranteLadoEsquerdo_id , restauranteLadoDireito_id) values (4, 5, 1)
insert into possivel_escolha (id, restauranteLadoEsquerdo_id , restauranteLadoDireito_id) values (5, 3, 2)
insert into possivel_escolha (id, restauranteLadoEsquerdo_id , restauranteLadoDireito_id) values (6, 4, 2)
insert into possivel_escolha (id, restauranteLadoEsquerdo_id , restauranteLadoDireito_id) values (7, 5, 2)
insert into possivel_escolha (id, restauranteLadoEsquerdo_id , restauranteLadoDireito_id) values (8, 4, 3)
insert into possivel_escolha (id, restauranteLadoEsquerdo_id , restauranteLadoDireito_id) values (9, 5, 3)
insert into possivel_escolha (id, restauranteLadoEsquerdo_id , restauranteLadoDireito_id) values (10, 5, 4)
